### ISSUE TITLE
Telegram Web: Night Theme Background

### ISSUE THREAD

**Issue by jovancosta** [zhukov/webogram#1890] opened 2019-08-29 02:53 UTC
Please, configure a night theme background option for telegram web. It would help a lot of users that use telegram during the night. And not only the message area. But the whole interface, just like a night theme used for other websites.

**Comment by nazimjamil** [comment] 2019-09-30 11:27
Seems to be a dupe of an open issue / PR > https://github.com/zhukov/webogram/pull/1840

**Closed** 2020-02-19 21:21 UTC
