### ISSUE TITLE
Chrome on android doesn't keep session

### ISSUE THREAD

**Issue by Yehonal** [zhukov/webogram#785] opened 2015-04-24 12:39 UTC
Everytime i login on web interface it doesn't keep the session, in fact after restart i've to relogin and waiting for the code.

I'm using Galaxy S4 with android lollipop and latest version of Chrome

**Comment by ArtemFitiskin** [comment] 2015-04-26 16:14
Is your browser supports HTML5 LocalStorage? [Simple fiddle](https://jsfiddle.net/ArtemFitiskin/avw7d54b/) to test it right now.

**Comment by Yehonal** [comment] 2015-04-26 16:57
Yes it is. And your test runs well

**Comment by zhukov** [comment] 2015-04-28 11:42
How did you install Lolipol on S4 ? I have the same phone and it says the most recent version is 4.4.2.

**Comment by Yehonal** [comment] 2015-04-28 11:45
In my country there is the official upgrade via OTA

**Comment by zhukov** [comment] 2015-04-28 12:08
I've just tried, I can't reproduce this situation with default settings.

Can you check you browser settings for some option to disable storage? E.g:

Privacy -> Do not track
Site settings -> Cookies
Site settings -> Storage -> find web.telegram.org
Site settings -> All sites -> find web.telegram.org

Or may be you have some other 3rd party software for cleaning OS etc..

**Comment by Yehonal** [comment] 2015-04-28 14:16
After various tests, i found a "workaround": new versions of chrome introduced new features of "tabs in app switcher". If you disable it, as i did , seems telegram doesn't keep session when i close chrome ( it doesn't happen with other web apps like facebook ). With this feature enabled instead telegram keeps the session.

**Comment by zhukov** [comment] 2016-06-10 13:26
Just tried S4 and S5 with Android 5. Can't reproduce anymore.
I guess it was fixed in Chrome or it was some 3rd party software.

**Closed by zhukov** 2016-06-10 13:26 UTC
