### ISSUE TITLE
Notifications not sent when web.telegram.com page is closed 

### ISSUE THREAD

**Issue by aghasemi** [zhukov/webogram#1257] opened 2016-10-30 21:43 UTC
Hi,
HTML5 notifications work only when the messenger page is open in Browser. Is that true?

I have seen websites that send notifications even when closed (using Web Workers?). so it seems possible, and really useful.

**Comment by marco-c** [comment] 2016-10-30 22:49
Duplicate of #981.

**Closed** 2016-11-17 16:54 UTC
