### ISSUE TITLE
Add a Share on Telegram option to the Firefox OS' share functionallity

### ISSUE THREAD

**Issue by sergioad** [zhukov/webogram#646] opened 2015-01-07 03:24 UTC
Hello @zhukov can you add a share on Telegram option to the Firefox OS' share menu?

**Comment by zhukov** [comment] 2015-01-08 11:18
I beleive this code https://github.com/zhukov/webogram/blob/master/app/js/services.js#L2010 
should allow you share photos via Telegram.
So what is the exact problem? What do you want to share? Can you show screenshots?
Is there an API for it?

**Comment by sergioad** [comment] 2015-01-08 15:50
Niope, for example when you are on the galery or the web browser you can share content like images or URLs directlly from the mentioned apps but there is not an option to share on Telegram

**Comment by Ryuno-Ki** [comment] 2015-01-10 12:21
That's strange, since the manifest contains [an activity for that](/zhukov/webogram/blob/7412a02ef1778b026d0e0e2bb20d107cd581de18/app/manifest.webapp#L49). I'll need to check it on my device.

@zhukov The steps to reproduce - as I understand it - are such:

 1. Open the gallery and pick a photo.
 1. Choose the option to share that photo.
 1. Expected: Find Telegram as one destiny for sharing, but as @sergioad moans, it doesn't show up there.

@sergioad Can you tell me, which device you are using? Which version of Firefox OS is it running?

**Comment by sergioad** [comment] 2015-01-11 04:39
@Ryuno-Ki Alcatel one touch fire Firefox OS 2.0

**Comment by Ryuno-Ki** [comment] 2015-01-11 10:13
Cannot confirm it for Alcatel OneTouch Fire running Firefox OS 1.3.

**Comment by rmed** [comment] 2015-01-11 13:27
Firefox OS 2.1 (Flame) here, Telegram does appear as an option in applications such as Gallery, Music, etc. However, the **browser** only displays two options for sharing a link (text message and e-mail). I'd say it's more of a B2G-related issue.

**Comment by sergioad** [comment] 2015-01-11 23:53
@rmed I had 2.1 too

**Comment by Rayonant** [comment] 2015-01-16 02:31
Here on a ZTE Open running Firefox OS 2.0 the sharing option does appear
![2015-01-15-21-30-35](https://cloud.githubusercontent.com/assets/7349563/5770754/e7796f9a-9cfd-11e4-9244-53a41636db39.png)

**Comment by zhukov** [comment] 2015-01-16 09:00
I guess, that this is a problem of B2G then.
We register a 'share' activity listed here: https://developer.mozilla.org/en-US/docs/Web/API/Web_Activities, It worked fine on my Fx OS v1.3.

Closing the issue for now. Feel free to open, if we figure out that a problem is on our side.

**Closed by zhukov** 2015-01-16 09:00 UTC
