### ISSUE TITLE
Implement WhatsApp-like audio recording?

### ISSUE THREAD

**Issue by orschiro** [zhukov/webogram#1345] opened 2017-02-17 08:22 UTC
Dear all, 

I would like to suggest to implement an audio recorder directly into the web interface, similarly to WhatsApp Web. This would greatly enhance the user experience. 

What do you think?

Yours,

Robert

![image](https://cloud.githubusercontent.com/assets/170947/23057922/a9bb6fba-f4f2-11e6-9297-fe64a60372be.png)

**Comment by MalesLabs** [comment] 2017-02-18 15:24
I think it's a great idea

**Comment by orschiro** [comment] 2017-02-18 15:29
I think so, too. :-)

Can it be done technically?

**Comment by Ryuno-Ki** [comment] 2017-02-21 19:28
I was collaborating with @TitanNano on that in #840. He wanted to redo it, because the PR got stalled.

I would consider this issue as duplicate of #190.

**Comment by orschiro** [comment] 2017-02-21 20:12
Wow, great to see it's basically already there.

Thanks for your work on this! :-)

**Comment by zhukov** [comment] 2017-03-14 14:44
Yep, duplicate #190.

**Closed by zhukov** 2017-03-14 14:44 UTC
