### ISSUE TITLE
[FxOS] CORS blocked on 2.0

### ISSUE THREAD

**Issue by willyaranda** [zhukov/webogram#372] opened 2014-07-08 09:00 UTC
I'm facing the CORS blocking on 2.0. The bug that introduced this is: https://bugzilla.mozilla.org/show_bug.cgi?id=713980

I think we could test it with a `systemXHR` as stated in https://github.com/zhukov/webogram/issues/355#issuecomment-47702885  but I think this is in the root of angular, seeing the requests :(

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://173.240.5.1/apiw1. This can be fixed by moving the resource to the same domain or enabling CORS.
```

**Comment by zhukov** [comment] 2015-01-16 11:29
According to https://developer.mozilla.org/ru/docs/Web/Apps/Reference:

> ### systemXHR
> 
>Allows anonymous (no cookies) cross-origin XHR without the target site having CORS enabled. Similar to the TCP Socket API but restricted to XHR, not just raw sockets, so it is slightly less risky. See XMLHttpRequest.

Telegram API DOES have CORS enabled, so I this we don't need systemXHR (Telegram Web works well in usual browsers without any permissions via usual Ajax with CORS). It also works with FxOS 1.3. So I guess, the problem is on FxOS 2.0 side.

Closing the issue then. If you have any more proved information about FxOS 2.0 and CORS, please reopen the issue.

**Closed by zhukov** 2015-01-16 11:29 UTC
