### ISSUE TITLE
Change "Log out" location (Menu -> Settings -> Log out)

### ISSUE THREAD

**Issue by Jonadabe** [zhukov/webogram#1832] opened 2019-03-25 21:51 UTC
I didn't saw the location of logout button until I was writing this issue.

Any good reason for hiding the logout button so deep???

I found the location of the button in this "Enhancement: Add "Close current session" or "Disconnect" button" https://github.com/zhukov/webogram/issues/787

Thanks.

**Comment by zhukov** [comment] 2019-05-09 21:17
Duplicate of #1180

**Closed by zhukov** 2019-05-09 21:17 UTC
