### ISSUE TITLE
Emoji's should stay open with a click

### ISSUE THREAD

**Issue by curciel** [zhukov/webogram#792] opened 2015-05-02 12:59 UTC
Emojis shows when the mouse is over it but in Tablet there's no mouse, so I can't use emojis.

It would be great an option for not asking to change mode to desktop or mobile on each change of size.

**Comment by zhukov** [comment] 2015-06-30 14:34
Second line is a duplicate of #585.

As for the first one, this was fixed and will be in master soon.

**Closed by zhukov** 2015-06-30 14:34 UTC
