### ISSUE TITLE
Chat text is blured after scroll

### ISSUE THREAD

**Issue by kabantejay** [zhukov/webogram#1506] opened 2017-09-20 21:14 UTC
text in chat is blured after i scroll, it shown on the screen in attach
 i use the latest chrome browser
![default](https://user-images.githubusercontent.com/9472648/30667960-e315f5dc-9e61-11e7-8362-904781899321.png)

**Comment by miiichael** [comment] 2017-09-22 05:35
Isn't this a duplicate of #1486?

**Comment by AlexByte** [comment] 2017-11-20 14:16
@miiichael yes

**Comment by zhukov** [comment] 2017-12-04 16:46
Duplicate of #1486

**Closed by zhukov** 2017-12-04 16:46 UTC
