### ISSUE TITLE
Suggestion: Dark Theme

### ISSUE THREAD

**Issue by Nhoya** [zhukov/webogram#654] opened 2015-01-16 11:47 UTC
Hey there, i use telegram as my Primary IM and for work's contacts too.. Lot of times i works at night and the white/blue colors make my eyes bleeding... What about a dark theme? I did this (really, seriously really, dirty) css http://l33tspace.altervista.org/repo/dark-telegram/ and i think that the colors path could bee nice and i think that someone could makes it really better

**Comment by anewuser** [comment] 2015-04-21 13:06
Duplicate of https://github.com/zhukov/webogram/issues/592

**Comment by zhukov** [comment] 2015-04-23 11:29
Yeah. We now have LESS for stylesheets. You can move all necessary colors, images, backgrounds variables to separate file and create modified version. And this might be a very useful PR ;)

Closing the issue.

**Closed by zhukov** 2015-04-23 11:29 UTC
