### ISSUE TITLE
Not all the conversations are visible in the web client, only 2 or 3 instead of 15-20

### ISSUE THREAD

**Issue by mcagl** [zhukov/webogram#649] opened 2015-01-10 20:33 UTC
Since today I experience problems with the web client.

I had many conversations (group chats, some old non-secret 1:1 chats, etc) and now I have only 2 or 3 (on the smartphone they're accessible, but not anymore on the web client).

Before that, I had sync problems (accessing one groupt chat, for example, did not sync the right way, many messages were missing).

I tried also to logout from the web client, then re-login (getting a new code and so on), but the situation didn't change.

**Comment by zhukov** [comment] 2015-01-10 20:48
This is a known bug, which was fixed in recent releases. What version are you using?

**Comment by mcagl** [comment] 2015-01-10 20:56
Thanks for the quick response, the bug is on the web.telegram.org website client.

I did a search that gave, as a result, an old (not visible) 1:1 chat, and clicking on that result reopened the chat, apparently with all the backlog. But even with the chat opened in the right pane, it did not appear in the left pane.

If it's useful, on my smartphone I'm using the last f-droid version: v2.1.1 (405) (but I did not make an upgrade recently, so I don't know what could have been triggered the bug in the web client today).

I just tried with the linux desktop client, and the bug is not reproduced here.

**Comment by zhukov** [comment] 2015-01-10 22:19
I asked for webogram version. Can you check that in settings? Also, what bowser are you using?

**Comment by mcagl** [comment] 2015-01-10 22:24
* 0.3.8, the one on the official website
* Firefox 34.0 from Mozilla's tar.gz package
* Debian testing

**Comment by zhukov** [comment] 2015-01-12 12:00
The actual version is 0.3.9. So this issue is a duplicate of #638.

Check this comment to clear appCache for Webogram in order to upgrade: https://github.com/zhukov/webogram/issues/638#issuecomment-69541710

**Closed by zhukov** 2015-01-12 12:00 UTC

**Comment by mcagl** [comment] 2015-01-14 01:49
Clearing the cache solved the problem, now the version that I find on web.telegram.org is 0.3.9.

Thanks @zhukov
