### ISSUE TITLE
Images and stickers in chats are too small

### ISSUE THREAD

**Issue by azzimuth** [zhukov/webogram#1275] opened 2016-11-22 09:18 UTC
Updated the code to the most recent. Now the images and stickers in chats became really small:
![webogram_bug2](https://cloud.githubusercontent.com/assets/1640148/20517794/00b6a306-b09d-11e6-9072-0e17d9cfe6aa.png)

**Comment by zhukov** [comment] 2016-11-22 15:26
Can't reproduce, everything is as before for me (and I think, I didn't touch this code).
What browser and OS?
did you try https://zhukov.github.io/webogram/ ? most recent version is here.

**Comment by azzimuth** [comment] 2016-11-22 15:34
Unfortunately (or luckily) I cannot reproduce this either. I tested on Windows 10 x64, Chrome 54.0.2840.99

**Comment by zhukov** [comment] 2016-11-22 15:42
Closing issue for now. Will reopen if reproduces.

**Closed by zhukov** 2016-11-22 15:42 UTC
