### ISSUE TITLE
Push notification on Firefox 

### ISSUE THREAD

**Issue by edoz90** [zhukov/webogram#1046] opened 2016-01-31 01:19 UTC
Firefox 44 now can get push notification from website (with permission): https://blog.mozilla.org/blog/2016/01/25/firefox-can-now-get-push-notifications-from-your-favorite-sites/

**Comment by marco-c** [comment] 2016-01-31 02:57
Duplicate of #981.

**Closed** 2016-01-31 15:02 UTC
