### ISSUE TITLE
Search for ".." results in an error

### ISSUE THREAD

**Issue by stefan-niedermann** [zhukov/webogram#802] opened 2015-05-21 11:25 UTC
i will add a screenshot if necessairy - just use the left top search to look for ".." - dot dot. there will be an error-pop-up.

**Comment by zhukov** [comment] 2015-05-21 11:26
What version are you using? I can't reproduce this.

**Comment by stefan-niedermann** [comment] 2015-05-21 11:37
Currently don't have access to webogram (am @ work). i think its the latest version of firefox marketplace.

**Comment by zhukov** [comment] 2015-07-26 19:11
This was fixed with #794.

**Closed by zhukov** 2015-07-26 19:11 UTC
