### ISSUE TITLE
Telegram web increases seriously cpu firefox process...

### ISSUE THREAD

**Issue by murrayf** [zhukov/webogram#662] opened 2015-01-25 09:51 UTC
Thanks and congrats!

Alberto.

:)

**Comment by zhukov** [comment] 2015-01-25 10:50
What browser and  OS versions? How are you using Telegram Web: web (which url) / packaged app / localhost ?

**Comment by murrayf** [comment] 2015-01-25 10:57
Hi Igor,

Sorry for omitting versioning details, here they are:

Mozilla Firefox 35.0 (Fedora 21)
https://web.telegram.org/#/im   (Telegram Web - Version 0.3.9)


When I open this url for using telegram web, firefox process rises to 
40% of CPU consum aproximately...

Thanks,

:)

----------
Alberto Segura.

El dom, 25 de ene 2015 a las 11:50 , Igor Zhukov 
<notifications@github.com> escribió:
> What browser and OS versions? How are you using Telegram Web: web 
> (which url) / packaged app / localhost ?
> 
> —
> Reply to this email directly or view it on GitHub.
> 
=

**Comment by guillermogf** [comment] 2015-02-15 23:43
Experiencing the same issue since last week or so. Only happens when Telegram is the focused tab.

Iceweasel (Firefox) 34.0 - Debian Testing. Linux 3.16 64 bits - Telegram 0.4.0 (web.telegram.org)

**Comment by Ryuno-Ki** [comment] 2015-04-13 22:34
I remember Firefox having an [about:memory](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/about:memory) tab. Memory leaks are often correlated to performance bottlenecks. Maybe you can look at it (or upload the content/take a screenshot).

Am I right in this problem only occurs in Firefox/Iceweasel, @guillermogf @murrayf?

**Comment by Ryuno-Ki** [comment] 2015-04-13 22:42
Maybe related to #241 …

**Comment by guillermogf** [comment] 2015-04-14 15:10
I haven't tested it with any other browser.

about:memory doesn't report any increase in memory usage when cpu usage raises after focusing on webogram tab.

**Comment by murrayf** [comment] 2015-04-14 15:40
Hi,

... It seems a firefox browser only issue. I've have tested web 
telegram with gnome web browser and there is not such cpu increase.

:)

-----------------
Alberto Segura.

**Comment by guillermogf** [comment] 2015-06-17 12:55
I'm not experiencing this issue any longer. I haven't done anything but updating Firefox. Now using version 38.
Don't know if it is because of firefox's or webogram's updates.

**Comment by mirh** [comment] 2016-03-01 12:50
I have this problem in both Firefox 44 and MS edge. 
..
Could it have something to do with about 30000 messages waiting to be read in a group?

**Comment by kmg90** [comment] 2016-03-29 20:46
Something is going on, seems to be a CPU leak as the CPU usage increases as the web page is open. GIFs seem to add significant load but understandable since they can be demanding however disabling them (clicking on them to stop them from animating) doesn't lessen the CPU usage and the only workaround is to reload the page which is not ideal.

**Comment by steffen-mueller** [comment] 2016-03-31 09:11
With Chrome 49 on Win10, something similar happens. It completely relates to the gif selection dialog - after searching for a GIF, the GPU (!) Load according to the chrome task manager rises from 2-3% before to a constant 10+%. Reloading the tab fixes it.
The effect causes the fans of my Surface Pro 3 to spin (this is how i recognized).

So, the problem does not seem to be related to Firefox, but rather a general problem. If I had to guess, I would guess that the Video Elements from the GIF selection dialog are still running off-screen...

**Comment by notnsane** [comment] 2016-04-20 17:41
I'd like to add my tests on Vivaldi browser, which is technically a fork of Chrome with a JS-based UI.

I'm using it as a Web Panel right now (to test it) and this is the performance markup I'm getting:

![l5kae90](https://cloud.githubusercontent.com/assets/7162375/14684237/674afadc-0705-11e6-9deb-a050745a8362.png)

It's very important to notice that this CPU % usage **only happens when I'm in Message View - that's it, when having a conversation opened**. As such, this doesn't happen when in General View.

The CPU usage is consistent in the sense **that it's never idle, it's never 0%**, and uses an average of 4-5% CPU process, which is really bad. Telegram Web should only try to update every X seconds. Does this make sense?

@zhukov 

If you need more info, please ask. This can be reproduced with Vivaldi 1.0 stable and latest snapshot (1.1 is due soon), and I'm using Windows 10 x64 with Vivaldi x86 build.

**Comment by floooat** [comment] 2016-04-23 19:32
same here, very high cpu usage - especially with gifs...

**Comment by Hedaja** [comment] 2016-06-09 01:28
Firefoxe's new about:performance tool also shows an increased CPU usage. I saw it between 8 and 18% which is still very high for a chat window.

Firefox 48.0
Ubuntu 16.04
Telegram Web Version 0.5.4

**Comment by oidualc** [comment] 2016-06-22 10:12
I can confirm the issue, I'll try to add some information to help debugging the issue.
You can easily reproduce it by calling the Giphy bot, as soon as you hit space after '@gif' it loads the selection of gifs and it starts eating up the CPU. Interestingly, after you close the little panel containing the images, the CPU keeps running at full speed.
It seems the CPU starts running after a call to the jquery library.

Using Chrome 53 on linux.

**Comment by serv** [comment] 2017-07-29 02:35
No one complained since 2016. I would say we close this one.

**Comment by stek29** [comment] 2017-07-29 07:46
@serv "We"? You've never experienced this issue, you're not issue creator, you're not collaborator and you're not a contributor. Have you even commented on issues before?

Sorry for being rude. I understand that you're just trying to clean up open issues, I haven't wanted to offend you.

**Comment by serv** [comment] 2017-07-29 17:41
I was working based on the convention other large projects follow. My bad.

What do you think? Do you think this issue is still relevant?

**Comment by murrayf** [comment] 2017-07-29 17:56
You can close it if you want, but cpu usage is high.

**Comment by serv** [comment] 2017-07-29 17:58
Is it still very high for you?

**Comment by murrayf** [comment] 2017-07-29 18:02
maybe it is a little high but it is probably caused because of a 
elevated number of channels in my telegram (15-20).

Close it, no problem!

Alberto.

:)

**Comment by mirh** [comment] 2017-07-30 10:35
> elevated number of channels in my telegram (15-20)

That still smells like a problem

**Comment by nkittsteiner** [comment] 2017-12-29 23:06
When you have 4 or 5 heavy message channels, I get nearly 100% CPU un a Macbook Pro with 8 CPUs, it's similar when some web page do XMR mining with your browser (looks suspicious).

**Comment by zhukov** [comment] 2017-12-30 06:52
@nkittsteiner Also Firefox? Easily reproduces? Can you try to launch webogram on localhost, reproduce and check, what functions are eating cpu?

**Comment by Ryuno-Ki** [comment] 2018-01-04 19:28
Maybe you could record some information from the [Profiler tab](https://developer.mozilla.org/en-US/docs/Tools/Performance) as a screencast and share it. Make sure the resolution is high enough to be able to read the lines.If you move the DevTools to a separate window and only record that one, privacy of the channels should be preserved.

**Closed** 2020-02-19 18:50 UTC
Labels: duplicate
