### ISSUE TITLE
Suggestion: Dock app icon to the right side of the shelf in Chrome OS like Hangouts

### ISSUE THREAD

**Issue by noahleigh** [zhukov/webogram#707] opened 2015-02-20 19:01 UTC
In Chrome OS, the [Hangouts extension](https://chrome.google.com/webstore/detail/hangouts/nckgahadagoaajjgafhacjanaoiihapd?utm_source=chrome-app-launcher-search) places an icon in the shelf that isn't a normal app icon, but is right-aligned and shows the conversation list as a bubble instead of a window. 
![screenshot 2015-02-20 at 1 52 19 pm](https://cloud.githubusercontent.com/assets/5957867/6307270/827e3d42-b908-11e4-8934-d3dd55638bb0.png)
Would it be possible to implement something similar for Telegram to reduce window management and allow quicker access to conversations?

**Comment by andmalc** [comment] 2015-02-22 23:42
You can get a window similar to Hangouts with the Chrome 'Panel Tabs' extension which can turn any web page into a smaller, minimal window that is always on top and can be minimized by its icon at the lower right of the ChromeOS like in your screenshot.   If you reduce the window's width enough it will prompt to switch to the mobile version and hide the contact list.

![screenshot 2015-02-22 at 6 37 29 pm](https://cloud.githubusercontent.com/assets/856605/6321193/5b48b5fc-bac2-11e4-91ce-b2717d363c00.png)

**Comment by zhukov** [comment] 2015-02-23 16:18
Duplicate of https://github.com/zhukov/webogram/issues/90.

(I don't understand, why this can be done by extension and not a Chrome App, since I think Chrome App suits better for messaging).

**Closed by zhukov** 2015-02-23 16:18 UTC
