### ISSUE TITLE
Bug: No Notifications on Firefox OS without starting Telegram first

### ISSUE THREAD

**Issue by stephenjudge** [zhukov/webogram#667] opened 2015-01-27 10:17 UTC
I can't find any existing issue for this, maybe there are not many people using Telegram as a Firefox OS app. When using Telegram on a Firefox OS device, I do not receive a notification of a received message unless I have first launched Telegram. I am not sure what version of Firefox OS I using, but I have the latest version sent over an OTA update on a ZTE Open C. I will find the Firefox OS version and update this issue. I installed Telegram from the Firefox Marketplace https://marketplace.firefox.com/app/telegram

What happens:
- Turn on my phone
- Someone sends me a message
- I don't receive a notification of a message received
- I am impatient so I open the Telegram app, then I see there is a new message waiting for me to read in the app.

What should happen:
- Turn on my phone
- Either leave the screen active or lock the screen
- Someone sends me a message
- I should receive a system notification either on my active screen or my lock screen, which I can see and tap on to be brought to the message in Telegram.

Workaround:
- I have to turn on my phone
- Then immediately launch Telegram to activate the app
- Return to my home screen and continue using my phone or lock my phone, leaving Telegram running in the background
- When I receive a message, I do now get a notification on my lock screen, or my active home screen.

**Comment by TitanNano** [comment] 2015-01-28 17:43
I described the actual problem in #655

**Comment by zhukov** [comment] 2015-01-29 10:14
Duplicate of #655.

**Closed by zhukov** 2015-01-29 10:14 UTC
