### ISSUE TITLE
Gulp build process fails because of gulp-usemin

### ISSUE THREAD

**Issue by guystein** [zhukov/webogram#971] opened 2015-11-17 13:07 UTC
![screen shot 2015-11-17 at 3 06 29 pm](https://cloud.githubusercontent.com/assets/13539585/11212185/d5864472-8d3c-11e5-982e-40c14e5a1fff.png)

**Comment by guystein** [comment] 2015-11-17 13:07
To fixed it i manually installed gulp-usemin version 0.3.11:
npm uninstall gulp-usemin
npm install gulp-usemin@0.3.11

**Comment by marco-c** [comment] 2015-11-25 16:52
Duplicate of #956?

**Comment by zhukov** [comment] 2015-11-26 10:16
Yes.

**Closed by zhukov** 2015-11-26 10:16 UTC
