### ISSUE TITLE
The message is not supported on your version of Telegram Web. Update the app to view: web.telegram.org

### ISSUE THREAD

**Issue by coari** [zhukov/webogram#1895] opened 2019-09-07 11:56 UTC
The message is not supported on your version of Telegram Web. Update the app to view: web.telegram.org.

All the time see this! How to solve?

**Comment by ogghi** [comment] 2019-09-09 14:04
Yeah, it is when animated stickers come in...is this on the future list to be supported?

**Comment by sirtoobii** [comment] 2019-09-19 15:47
Duplicate of
#1850

**Comment by Aokromes** [comment] 2020-02-19 18:13
well, without link to the exact message we cannot know what's the afected feature.

**Comment by mschumacher69** [comment] 2020-02-19 19:44
I guess this is for animated stickers.

**Comment by Aokromes** [comment] 2020-02-20 06:05
well, if it's animated stickers
https://github.com/zhukov/webogram/issues/1874

**Closed by Aokromes** 2020-02-20 06:05 UTC
Labels: Waiting for Answer
