### ISSUE TITLE
Name with emojis is not displayed correctly in Notifications

### ISSUE THREAD

**Issue by termoyer** [zhukov/webogram#831] opened 2015-06-18 22:18 UTC
Hey,
i'm using Firefox (Version: 40.0a2 (2015-06-18)) on Windows 8.1 to access telegram on web. My Problem is that Names are not displayed correctly when i get a notification. If there are emojis in the name, the "value" of the emoji is displayed instead of the emoji itself.
See it yourself:
Instead of this
![unbenannt](https://cloud.githubusercontent.com/assets/4527344/8243504/ce50b300-1617-11e5-84e2-5a9122a10195.png)
it should show the name like this
![unbenannt1](https://cloud.githubusercontent.com/assets/4527344/8243525/07cf30ca-1618-11e5-84d4-a5742b6e4240.png)

It worked fine until today.

Thanks in advance

**Comment by zhukov** [comment] 2015-06-30 11:15
That's a feature. Since your OS doesn't support emoji natively, we can't display notifications as is (otherwise black squares would be displayed), so we replace it with text alt.

**Comment by zhukov** [comment] 2015-06-30 11:32
Possibly duplicate of #451. Please continue there.

**Closed by zhukov** 2015-06-30 11:32 UTC
