### ISSUE TITLE
Improve reply UX

### ISSUE THREAD

**Issue by Shaunakde** [zhukov/webogram#816] opened 2015-05-28 16:20 UTC
The reply feature on Android is very addictive and useful in conversations. Can this be reproduced on the web interface?

**Comment by hebrew878** [comment] 2015-05-28 16:31
it is already there in web interface.

**Comment by Shaunakde** [comment] 2015-05-28 16:34
I skimmed the documentation and could not find it. Could you point it out
here so future searches produce correct results.

**Comment by hebrew878** [comment] 2015-05-28 16:44
![tg](https://cloud.githubusercontent.com/assets/2658040/7865486/cf02a782-0586-11e5-89e3-484774e46b86.png)

**Comment by Shaunakde** [comment] 2015-05-28 17:11
This is what my interface looks like:
![capture](https://cloud.githubusercontent.com/assets/2545129/7866074/9fbca4a6-058a-11e5-958d-e9a992e1e0a8.PNG)

**Comment by Shaunakde** [comment] 2015-05-28 17:13
Okay, I found the feature. Writing it down to document it:
Click on the "Edit" button on the top right.
Select the message to reply to.
Reply will pop up.

**Comment by bb010g** [comment] 2015-05-28 22:33
If the issue is resolved, please close it.

**Comment by Walkman100** [comment] 2015-05-29 02:57
I do agree though, that it is very difficult to reply to a message on Webogram: on Telegram Mobile you tap and hold a message and tap reply, on Telegram Desktop you right click -> reply, while on Webogram you have to go through a series of steps to get the same thing... It's not very user friendly, and should be made easier (not that I know how to :disappointed:)

**Comment by mattrick16** [comment] 2015-05-30 06:00
If you hover over the message to the left, you'll see a check mark. If you click on it, it will allow you to reply. No need to click "Edit" ;)

**Comment by Walkman100** [comment] 2015-05-30 16:33
Ok, but still three clicks as opposed to the other client's two... I guess it's not so bad :smile:

**Comment by thob** [comment] 2015-05-31 14:08
Im on 0.4.4 I can click edit and get forward or delete but no reply, I don't see a checkmark while hovering over a message

**Closed** 2015-07-09 10:48 UTC
Labels: ready
