### ISSUE TITLE
Idea: Deleting message within a specific time and more

### ISSUE THREAD

**Issue by SiluPanda** [zhukov/webogram#1820] opened 2019-02-24 05:00 UTC
Some possible ideas and improvements in the web version:
1. Feature to delete a sent message within a specific time period (let's say 15 seconds). This is just to avoid sending anything wrong to the wrong person mistakenly. Instead of enabling delete at anytime, this sounds a little better.
2. Feature to switch between dark or light theme. (or even more customized themes)
Users can also submit themes.
3. sent/delivered receipts?
4. Private and public profiles. Let's say, I am in a group, and anyone in the group can message me in the current version. If I have a private profile, only my contacts can message me.
5. "Forwarded" tags on forwarded messages.

**Comment by stek29** [comment] 2019-03-02 21:30
> 1. Instead of enabling delete at anytime, this sounds a little better.

It's not anytime, it's 48 hours. And it's an api issue.

> 2. Feature to switch between dark or light theme

Duplicate of #1100.

> 3. sent/delivered receipts?

There are sent (1 tick) and read (2 ticks) receipts already.
Define delivered. If I'm out of home somewhere with no internet, and message is delivered to my iPad, does that count as delivered?
Also an API issue and a wontfix, lack of delivered status is a feature since delivered makes no sense in context of telegram.

> 4. Private and public profiles. 

API issue.

> 5. "Forwarded" tags on forwarded messages.

There is a forwarded tag.

**Closed by stek29** 2019-03-02 21:30 UTC
