### ISSUE TITLE
main CSS file missing

### ISSUE THREAD

**Issue by Jr750ac** [zhukov/webogram#1261] opened 2016-11-07 08:53 UTC
in index.html cite "<link rel =" stylesheet "href =" css / app.css "/>", but the file does not exist

**Comment by stek29** [comment] 2016-11-07 15:52
Duplicate of #756. See [this](https://github.com/zhukov/webogram/issues/756#issuecomment-91194898) for solution. And pls RTF[readme].

**Closed** 2016-11-17 16:51 UTC
