### ISSUE TITLE
Stickers can't display on Palemoon 26

### ISSUE THREAD

**Issue by roytam1** [zhukov/webogram#1104] opened 2016-04-06 03:41 UTC
```
[11:38:38.915] TypeError: asm.js type error: duplicate name 'n' not allowed @ https://web.telegram.org/js/app.js:22
[11:38:39.940] <source> element has no "src" attribute. Media resource load failed. @ https://web.telegram.org/#/im?p=s1002709485_8962928155109211064
[11:38:39.940] All candidate resources failed to load. Media load paused. @ https://web.telegram.org/#/im?p=s1002709485_8962928155109211064
[11:38:44.794] "Error: e is undefined
d@https://web.telegram.org/js/app.js:27
n/r</<@https://web.telegram.org/js/app.js:47
l@https://web.telegram.org/js/app.js:13
c/<@https://web.telegram.org/js/app.js:13
m.prototype.$eval@https://web.telegram.org/js/app.js:13
m.prototype.$digest@https://web.telegram.org/js/app.js:13
m.prototype.$apply@https://web.telegram.org/js/app.js:13
o/c<@https://web.telegram.org/js/app.js:13
a@https://web.telegram.org/js/app.js:12
at/u.defer/n<@https://web.telegram.org/js/app.js:12
n@https://web.telegram.org/js/app.js:3
"
[11:38:47.015] UnknownError @ https://web.telegram.org/js/app.js:27
[11:38:47.015] "Error creating/accessing IndexedDB database" [object Event]

```

**Comment by zhukov** [comment] 2016-06-10 12:29
We don't have support for Palemoon, I have no way to launch it. Works fine for me on the Firefox 46.
Please try to lauch the code on the non-minified version and provide full stack trace of the error.
Closing the issue for now. Feel free to open if we get the data.

**Closed by zhukov** 2016-06-10 12:29 UTC

**Comment by marco-c** [comment] 2016-06-10 12:35
I guess the problem is that Palemoon 26 uses a very old version of Gecko.
